ALTER TABLE public.routes
ADD COLUMN IF NOT EXISTS route_cost_inr NUMERIC,
ADD COLUMN IF NOT EXISTS baseline_cost_inr NUMERIC,
ADD COLUMN IF NOT EXISTS savings_inr NUMERIC,
ADD COLUMN IF NOT EXISTS travel_hours NUMERIC,
ADD COLUMN IF NOT EXISTS baseline_distance_nm NUMERIC,
ADD COLUMN IF NOT EXISTS fuel_saved_ton NUMERIC;
